### PR TITLE
Fix parse fields after bit[17-24] call.

### PR DESCRIPTION
**Pull request by entertainyou**
For bits with length in range of [17, 24], should only read 3 bytes for processing.

### CODE REVIEW

**Comment by entertainyou** [comment]
ping...

**Comment by entertainyou** [comment]
ping @keichi

**Comment by keichi** [comment]
I'm really sorry for the extremely late reply... Thanks for the work you have done here.
I can see that you have added `prefixLengthType` option. How is it related to `bit[17-24]` methods?

**Comment by entertainyou** [comment]
It's not related, pushed additional commits to the same pull request branch by mistake, the new three commit should be an another pull request, should I break the commits to two pull request?

**Comment by keichi** [comment]
Yes, please split your PR into two.

**Comment by entertainyou** [comment]
I've rewriten the history, :)

**Comment by keichi** [comment]
Thanks!

**Pull request merged**
