### PR TITLE
feat: add ESM package export

### PR DESCRIPTION
**Pull request by manzt**
Thank you for your work on this excellent project. 

This PR adds an extra build step to produce a "pure" ESM entrypoint for `binary-parser`. [ESM](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Modules) is now natively supported in Node>12 and all major browsers.

The postscript to add an `.mjs` extensions to the TSC output is added because 1.) the package.json is not set to `"type": "module"`, and 2.) ESM does not allow for relative imports without file extensions (so `import ... from "./context"` cannot be resolved by the Node ESM resolver or in browsers). ESM is additionally a desirable target for bundlers. 

Finally, if the polyfill for `TextDecoder` is removed, this script can be loaded natively in the browser via a local server (or a cdn).

```html
<script type="module">
import { Parser } from 'http://localhost:8080/dist/esm/binary_parser.mjs';

// in the future
import { Parser } from 'https://unpkg.com/binary_parser/dist/esm/binary_parser.mjs';
import { Parser } from 'https://cdn.skypack.dev/binary_parser'; // supports package exports fields

</script>
```

### CODE REVIEW

**Review by keichi — COMMENTED** [review]
Thanks @manzt! Can you please rebase this onto master? In addition, can you merge `context.ts` into `binary_parser.ts` and adjust `rename.js`? `context.ts` is a small file anyway, and merging it into `binary_parser.ts`  should make the post-build step simpler.

**Comment by manzt** [comment]
done!

**Comment by keichi** [comment]
Thanks! Yes, I've looked into esbuild but let's not overcomplicate things for now.

**Comment by keichi** [comment]
Just published a new release. Can you test if the ESM support works as expected?

**Comment by manzt** [comment]
Wonderful! Everything seems to be working:

```javascript
// package.json
{
  "name": "demos",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "dependencies": {
    "binary-parser": "^2.0.0"
  }
}
```

```javascript
// index.js
const { Parser } = require('binary-parser');
console.log(Parser);

// index.mjs
import { Parser } from 'binary-parser';
console.log(Parser);
```

```
~/demos is 📦 v1.0.0 via  v16.9.1 took 14s
❯ node index.js
[Function: Parser] { start: [Function (anonymous)] }

~/demos is 📦 v1.0.0 via  v16.9.1
❯ node index.mjs
[class Parser]
```

Additionally, you can import the package in the browser now directly:

https://observablehq.com/d/003b4f096ee7c6b2

**Pull request merged**
